konveyor/move2kube-tests

Dockerfile, Makefile
=> Make version of move2kube configurable

README.md
=> Added test execution instructions

README.md
=> Update slack to point to kubernetes workspace

data/plan/compose/m2k.plan, data/target/compose/myproject/m2kqacache.yaml
=> Update group name to konveyor.io

data/target/compose/myproject/myproject/apache-deployment.yaml, data/target/compose/myproject/myproject/apache-service.yaml
=> Update service name label

contributing.md
=> Add developer certificate to contributing.md

.github/workflows/test.yml, Makefile
=> Remove interactive mode from docker run

README.md
=> Fix badge urls

.github/workflows/prtest.yml, .github/workflows/release.yml, .github/workflows/test.yml
=> Fetch submodules before running test

.github/workflows/testtag.yml, README.md
=> Add test tag workflow

.github/workflows/testtag.yml
=> Rename test tag workflow

.github/workflows/testtag.yml
=> Add commit hash to notification message

.github/workflows/testtag.yml
=> Fix payload format

.github/workflows/testtag.yml
=> Fix env variable for docker-test

.github/workflows/assignproject.yml
=> Auto assign issues to project

Dockerfile, misc/centos.repo
=> Add support for minimal based move2kube image

.github/workflows/prtest.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/testtag.yml, Makefile
=> Add caching of images

.github/workflows/assignproject.yml, Dockerfile
- Name assign project workflow
- Use move2kube image as base image
=> changebaseimage

.github/workflows/assignproject.yml, .github/workflows/release.yml, .github/workflows/tag.yml
=> fix: release workflow to match the cli release workflow

.github/workflows/assignproject.yml, .github/workflows/prtest.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/testtag.yml
=> fix: typo in slack notification and reformatted workflow files

.grenrc.js
=> fix: add gren config file so it will generate the proper release draft

Dockerfile, Makefile
=> fix: Change default dir to workspace

Dockerfile, Makefile
=> fix: Optimize container image size and remove containers after run

.github/workflows/assignproject.yml, .github/workflows/prtest.yml, .github/workflows/release.yml, .github/workflows/tag.yml, .github/workflows/test.yml, .github/workflows/testtag.yml
=> ci: clean up workflows to work together across multiple repos

.github/workflows/release.yml, .grenrc.js
=> ci: create tag and create branch in release workflow

.github/workflows/release.yml
=> ci: we have to login before we can push

.grenrc.js, README.md
=> chore: update move2kube website url

data/expect/compose/script.exp, tests/commands.bats, tests/transform.bats_disable
=> fix: update command to transform from translate

Dockerfile
=> fix: Use fedora as base image for tests

.github/workflows/e2etest.yaml
=> chore: add the commit hash to the slack notification

e2etest-1-language-platforms.sh
=> fix: service name in e2e test on language platforms

e2etest-1-language-platforms-m2kconfig.yaml, e2etest-2-enterprise-app-m2kconfig.yaml, e2etest-3-train-ticket-m2kconfig.yaml
Signed-off-by: seshapad <seshapad@in.ibm.com>
=> fix: Qalabel patch

e2etest-2-enterprise-app-m2kconfig.yaml
=> fix: update the config file for the end-to-end test for enterprise app
